In [1]:
import numpy as np

In [4]:
rndnumber = np.random.random(50)

In [5]:
rndnumber

array([0.30063604, 0.23649163, 0.80807199, 0.3543427 , 0.47623301,
       0.00451098, 0.70187457, 0.11352971, 0.96325266, 0.59013489,
       0.17450371, 0.64387527, 0.64582144, 0.36701054, 0.55303598,
       0.02795409, 0.03706826, 0.34241236, 0.82050715, 0.1102681 ,
       0.08869749, 0.41693944, 0.05448739, 0.03724763, 0.32858751,
       0.92489551, 0.96223209, 0.51262601, 0.58536168, 0.7214532 ,
       0.31018554, 0.06166831, 0.66927297, 0.05511909, 0.0877973 ,
       0.94905345, 0.71518652, 0.41537744, 0.46286928, 0.0827761 ,
       0.56361375, 0.24091376, 0.30925827, 0.76298339, 0.41119683,
       0.42614801, 0.74535148, 0.48313967, 0.51278287, 0.64282491])

In [7]:
sum(rndnumber)

21.81158195194719

In [8]:
np.sum(rndnumber)

21.81158195194719

In [9]:
rndnumber = np.random.random(5000000)

In [10]:
%timeit sum(rndnumber)
%timeit np.sum(rndnumber)

1.38 s ± 98.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
9.63 ms ± 279 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%timeit min(rndnumber)
%timeit np.min(rndnumber)

754 ms ± 90.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
4.2 ms ± 80.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
%timeit max(rndnumber)
%timeit np.max(rndnumber)

700 ms ± 17.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
4.1 ms ± 105 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
rndnumber = np.random.random((3,30))

In [16]:
rndnumber

array([[0.05262345, 0.65462722, 0.2572736 , 0.57120268, 0.38881942,
        0.27556518, 0.09229047, 0.27972062, 0.75991874, 0.6005934 ,
        0.21384691, 0.89935448, 0.7253079 , 0.34296235, 0.36841929,
        0.03544698, 0.97757972, 0.73980073, 0.65262805, 0.57110231,
        0.05094529, 0.31995099, 0.01748454, 0.30898018, 0.72348893,
        0.23725885, 0.10169878, 0.23110877, 0.04421626, 0.02311713],
       [0.10713557, 0.57752237, 0.24373611, 0.21904381, 0.28209611,
        0.60519154, 0.35981443, 0.90535042, 0.94221903, 0.03645221,
        0.38025927, 0.88818533, 0.54423028, 0.96306732, 0.14303274,
        0.38931971, 0.67311484, 0.50872857, 0.33850813, 0.47268208,
        0.77883063, 0.61304143, 0.49040601, 0.5996071 , 0.96460674,
        0.12589595, 0.20530747, 0.87545144, 0.53912423, 0.325776  ],
       [0.04751343, 0.05507286, 0.06315903, 0.19068634, 0.80883938,
        0.57995575, 0.68821702, 0.64871023, 0.15586415, 0.20848955,
        0.31670935, 0.12530071, 0.33141313, 0.

In [19]:
sum(rndnumber)
np.sum(rndnumber, axis = 0)

array([0.20727245, 1.28722245, 0.56416874, 0.98093283, 1.47975491,
       1.46071247, 1.14032193, 1.83378127, 1.85800192, 0.84553516,
       0.91081553, 1.91284051, 1.60095132, 2.24720794, 1.32840973,
       1.385561  , 1.88861408, 1.92362743, 1.87983189, 1.63605658,
       0.84847573, 1.89431505, 0.71709791, 1.88386486, 2.08086943,
       0.4285791 , 0.38663604, 1.23779972, 1.22153665, 0.39190759])

In [20]:
np.nansum(rndnumber, axis = 0)

array([0.20727245, 1.28722245, 0.56416874, 0.98093283, 1.47975491,
       1.46071247, 1.14032193, 1.83378127, 1.85800192, 0.84553516,
       0.91081553, 1.91284051, 1.60095132, 2.24720794, 1.32840973,
       1.385561  , 1.88861408, 1.92362743, 1.87983189, 1.63605658,
       0.84847573, 1.89431505, 0.71709791, 1.88386486, 2.08086943,
       0.4285791 , 0.38663604, 1.23779972, 1.22153665, 0.39190759])

In [21]:
np.mean(rndnumber, axis = 0)

array([0.06909082, 0.42907415, 0.18805625, 0.32697761, 0.49325164,
       0.48690416, 0.38010731, 0.61126042, 0.61933397, 0.28184505,
       0.30360518, 0.6376135 , 0.53365044, 0.74906931, 0.44280324,
       0.46185367, 0.62953803, 0.64120914, 0.62661063, 0.54535219,
       0.28282524, 0.63143835, 0.23903264, 0.62795495, 0.69362314,
       0.1428597 , 0.12887868, 0.41259991, 0.40717888, 0.13063586])

In [22]:
np.std(rndnumber, axis = 0)

array([0.02698247, 0.26632563, 0.08848843, 0.17308081, 0.22736781,
       0.14979393, 0.24370879, 0.2567814 , 0.33606702, 0.23607851,
       0.06856655, 0.36228855, 0.16098079, 0.2873    , 0.28011122,
       0.38123728, 0.30353309, 0.09733082, 0.22536529, 0.05210726,
       0.35097573, 0.26216182, 0.19421781, 0.27275233, 0.23440309,
       0.0711693 , 0.05478917, 0.32981523, 0.25982072, 0.13822381])

In [24]:
np_array = np.array([4,65,7,4,23,5])

In [25]:
np_array

array([ 4, 65,  7,  4, 23,  5])

In [26]:
np_array < 50

array([ True, False,  True,  True,  True,  True])

In [27]:
np_array > 50

array([False,  True, False, False, False, False])

In [28]:
np_array == 50

array([False, False, False, False, False, False])

In [29]:
np_array <= 50

array([ True, False,  True,  True,  True,  True])

In [30]:
np_array >= 50

array([False,  True, False, False, False, False])

In [31]:
np_array != 50

array([ True,  True,  True,  True,  True,  True])

In [32]:
(2* np_array) < (2%np_array)

array([False, False, False, False, False, False])

In [33]:
np_array < 50

array([ True, False,  True,  True,  True,  True])

In [35]:
rndnumber=rndnumber[0]

In [36]:
rndnumber

array([0.05262345, 0.65462722, 0.2572736 , 0.57120268, 0.38881942,
       0.27556518, 0.09229047, 0.27972062, 0.75991874, 0.6005934 ,
       0.21384691, 0.89935448, 0.7253079 , 0.34296235, 0.36841929,
       0.03544698, 0.97757972, 0.73980073, 0.65262805, 0.57110231,
       0.05094529, 0.31995099, 0.01748454, 0.30898018, 0.72348893,
       0.23725885, 0.10169878, 0.23110877, 0.04421626, 0.02311713])

In [37]:
np.sum(rndnumber<0.5)

19

In [38]:
rnd_number = np.random.random((3,4))

In [39]:
rnd_number

array([[0.46550965, 0.6824751 , 0.04872707, 0.66464745],
       [0.15683703, 0.30993489, 0.44294329, 0.37465995],
       [0.81666302, 0.77279141, 0.05461713, 0.15609879]])

In [40]:
np.sort(rnd_number, axis = 0)

array([[0.15683703, 0.30993489, 0.04872707, 0.15609879],
       [0.46550965, 0.6824751 , 0.05461713, 0.37465995],
       [0.81666302, 0.77279141, 0.44294329, 0.66464745]])

In [41]:
np.sort(rnd_number, axis = 1)

array([[0.04872707, 0.46550965, 0.66464745, 0.6824751 ],
       [0.15683703, 0.30993489, 0.37465995, 0.44294329],
       [0.05461713, 0.15609879, 0.77279141, 0.81666302]])

In [43]:
ar=np.array=[2,4,56,6,4,4,3,67,8,1]

In [44]:
ar

[2, 4, 56, 6, 4, 4, 3, 67, 8, 1]

In [45]:
np.partition(ar,2)

array([ 1,  2,  3,  6,  4,  4, 56, 67,  8,  4])

In [46]:
np.partition(ar,5)

array([ 1,  2,  3,  4,  4,  4,  6,  8, 56, 67])